### ISSUE TITLE
[功能请求] Linux和Mac的安装包

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/jmcomic-downloader#12]
### 原因

需要在Linux或Mac上使用

### 功能简述

Release页面添加Linux和Mac的安装包

### 功能逻辑

Release页面添加Linux和Mac的安装包

**Comment by lanyeeee** [comment]
真的有人需要么🤔

**Comment by yisishoujo** [comment]
按照构建步骤，总是在build_appimage.sh这里失败。Permission denied (os error 13) 

不过生成的rpm是可以用的，不得不吐槽编译接近完成整个文件夹1.9G，这个rpm就4M，确实应该提供安装包。
另外，ui字体太小，搜索结果的字体太大。

**Comment by lanyeeee** [comment]
> Permission denied (os error 13)  

这应该是Linux下权限的问题吧，我猜是构建时缺少啥库，它想自动帮你装然后没权限
提升权限试试，比如`sudo pnpm tauri build`


> 不得不吐槽编译接近完成整个文件夹1.9G  

这个大小是正常的，rust编译最终产物很小，但中间产物就是这么大，这1.9G还是精简后的发布版本。  
你可以试试`pnpm tauri dev`来运行调试版本，生成的文件夹估计能有10G

> ui字体太小，搜索结果的字体太大

在Linux上搜索结果字体大的离谱吗？跟README里的图片和视频相比(~~ui打算之后再慢慢优化，现在处于能用就行的状态~~)

**Comment by niuhuan** [comment]
不知您是否有意增加工作流自动构建并上传到Release，其打包内容的大小只有几Mib大小，我的PR只是一个建议，您如有需要可告知我稍作修改，亦可以关闭。

同时我有一些观点
1. 您的打包或许将运行时不必要的中间产物也构建了进去才会2G之大。
2. 于我对tauri的粗略了解，它的发布内容之所以很小可能是因为没有web运行时，部分平台（例如windows低版本）用户可能需要自行安装运行时，还需要对他稍加测试编写文档。

**Comment by lanyeeee** [comment]
目前由于webview的兼容性问题，暂时不打算发布其他端的安装包

我之前也在尝试用 github action 生成三端的安装包
测试时发现 linux 上的 `webkit2gtk-4.1` 存在一些问题，而Tauri v2的webview基于这玩意

例如，在Ubuntu 22.04上，使用代理时前端的webview无法向外网发送任何HTTP请求，这直接使项目中的 \<img src="xxx"/> 无法加载图片，导致封面都显示为空白
我给tauri提了issue不过没有得到答复，详情可以看
[wry](https://github.com/tauri-apps/wry) 的issue 1382
[tauri](https://github.com/tauri-apps/tauri/) 的issue 11251
(不直接给链接是不想把中文链过去)

甚至在Ubuntu24.04，`webkit2gtk-4.1` 还有跟NVIDIA显卡驱动不兼容导致的渲染问题，会导致页面全白

~~这就是体积小的代价，要是像electron那样带个浏览器就不会有这种问题了~~
