### ISSUE TITLE
[Bug] 获取收藏失败

### ISSUE THREAD

**Issue by cz249** [lanyeeee/jmcomic-downloader#13]
### 问题描述

 登录后显示获取收藏失败
我试着重启应用和重新登录都不行
 好像是这个错误引起的：将解密后的data字段解析为FavoriteRespData失败 invalid type: null, expected a string at line 1 column 75

ps：感谢您的工具~

### 预期行为

显示收藏夹内的本本

### 实际行为

获取收藏失败，收藏夹内没有可以下载的本本
![image](https://github.com/user-attachments/assets/a858626e-8470-4078-9adb-02a9f3ac9a60)

### 截图或录屏

完整报错：
0: 将解密后的data字段解析为FavoriteRespData失败: {"list":[{"id":"188475","author":"イシガキタカシ","description":null,"name":"[零食漢化組] [イシガキタカシ] 僕はあなたにワンと鳴く 第1-3話 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"3","title":"短篇"},"category_sub":{"id":null,"title":null}},{"id":"264883","author":"ぷぅ崎ぷぅ奈 ぷぅのぷぅぷぅぷぅ","description":"","name":"[新橋月白日語社漢化] [ぷぅのぷぅぷぅぷぅ (ぷぅ崎ぷぅ奈)] 人付き合いが苦手な未亡人の雪女さんと呪いの指輪 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"641717","author":"ミスターほっけ","description":"","name":"[ミスターほっけ]ニートレス","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"620549","author":"顔印象零","description":"","name":"[顔印象零] 雙子の玩具 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"627711","author":"ひょころー","description":"","name":"清純×反轉 ~精力這件事~ [驢子漢化組] [ひょこ道 (ひょころー)] 清楚×反轉 ~女友達がサキュバスに身體を乘っ取られて毎日精力供給させられる話~ [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"621958","author":"顔印象零","description":"","name":"[顔印象零] の天使 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"543503","author":"nocori","description":"","name":"被女友吃掉〜身體的抖S〜  [橄欖漢化組] [10時間睡眠 (nocori)] たべちゃうぞ♡〜ベタ惚れした清純派激カワ彼女に食われる俺の話〜 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"564036","author":"ろき","description":"","name":"[SweetEdda (ろき)] SweetEdda vol.3 サキュバス編 無邪氣な淫魔の少女メア","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"618046","author":"ディビ","description":"","name":"[ディビ] 手コース施術同意書 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"616282","author":"W","description":"","name":"[柯基個人漢化] [W] ェチの天使と惡魔がエッチする話 2","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"558108","author":"赤月みゅうと","description":"","name":"被我的魅魔三姊妹榨得一乾二淨 1-2","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"3","title":"短篇"},"category_sub":{"id":null,"title":null}},{"id":"60132","author":"關西オレンジ (荒井啓)","description":"","name":"(COMIC1☆8) [關西オレンジ (荒井啓)] Negative Love M2 (ラブプラス)","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"72270","author":"關西オレンジ (荒井啓)","description":"","name":"【禦萌漢化組】(COMIC1☆7) [關西オレンジ (荒井啓)] Negative Love M (ラブプラス)","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"75254","author":"","description":"","name":"[王道漢化] (C77) [雷神會 (はるきゲにあ)] ラブマナカ (ラブプラス)","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"607693","author":"赤佐たぬ 千露ぬい","description":"","name":"[XwX個人漢化] [赤佐研究所 (赤佐たぬ、千露ぬい)] 逝ぎだぐないッ!惡靈女に愛玩される男の娘","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"610053","author":"kinntarou","description":"","name":"(C104) [七轉八起 (kinntarou)] 身長211cmの地雷系女子に狙われてもう逃げら[中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"610056","author":"七崎","description":"","name":"(C104) [ハチナナ (七崎)] シスターにられる本 (シスター・クレア) [DL版] [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"611834","author":"海凪コウ","description":"","name":"[柯基個人漢化] [海凪コウ] 足湯體驗にようこそ","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"3","title":"短篇"}},{"id":"600750","author":"渡薫","description":"","name":"[渡薫] 純愛逆推 前篇 [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"3","title":"短篇"},"category_sub":{"id":null,"title":null}},{"id":"604672","author":"黒川リョーイチ","description":"","name":"[蔡徐坤個人漢化] [黒川リョーイチ] サキュバスの義妹にえっちなごっこ遊びでくる [中國翻譯]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}}],"folder_list":[],"total":"36","count":20}1: invalid type: null, expected a string at line 1 column 75

### 工具版本号

v0.1

**Comment by kingfirewxm** [comment]
当前版本（0.10.0）也出现了这个问题

**Comment by lanyeeee** [comment]
> 当前版本（0.10.0）也出现了这个问题

麻烦贴一下完整的报错信息

**Comment by kingfirewxm** [comment]
0: 将解密后的data字段解析为FavoriteRespData失败: {"list":[{"id":"387975","author":"李周元 颈枕","description":"过着平凡生活的南洙，某天不小心撞倒了阳台隔间，意外目睹青梅竹马的好身材!本以为这辈子和女人无缘的南洙，却从这一天开始和女人大小事纠缠不断。「要不要猜猜看，姊姊今天穿什么样的内裤啊?」","name":"小心你后面♥","latest_ep":"最终话 - 最后抉择","latest_ep_aid":"423536","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"502394","author":"Bbana Nammu19 薄荷巧克力饭糰","description":"泰裕因为嫌弃言情小说男女主角恋情进展太慢，结果被单身40年的魔法师作者惩罚，穿越到小说世界裡并附身在「王吕佑」身上。若想继续存活在这个光怪陆离的小说世界裡，就得抢走别人的女友！","name":"抢女友速成班\/抢女友速成班","latest_ep":"65","latest_ep_aid":"1025465","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"450291","author":"ゆげ けてる","description":"来到异世界魔法都市的开挂转生者‧拓海。他的目的是……「想和年轻女孩们一起玩！」　即使强如打到龙族的拓海，也因为怕死而从冒险者引退。　下一个野心便是做为一个「爸爸活大叔」享受生活。藉由萝莉老太婆妈妈桑精灵的帮助与堆积如山的财产，很顺利地笼络了年轻女孩。别忘了这裡是异世界。约会时突然出现怪物、在地下城迷路……，爸爸活也是得拼命的！　身为前S级冒险者的爸爸活大叔在此为你带来爱与感动以及充满性感魅力的冒险动作片――","name":"[禁漫汉化组]异世界爸爸活大叔 \/异世界パパ活おじさん","latest_ep":"29","latest_ep_aid":"1024904","image":"","category":{"id":"2","title":"单本"},"category_sub":{"id":null,"title":null}},{"id":"514852","author":"0103 千年Hwanhee 笔手","description":"不小心转生到弱肉强食武林世界的裕诚，还没来的及一捅天下，就受人陷害逃命天涯，最后只好躲到秘密洞穴裡苦练阴阳神功!没想到，注重交流结合的神功，还是需要女人一起双修，才能习得真传!","name":"色雕英雄传:一捅天下","latest_ep":"56","latest_ep_aid":"1020547","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"646603","author":"ImSoo-ah  TeamHarusari","description":"因为一场意外，基焕被召唤到了异世界。在这里，他体内龙的力量被激活了，但是却只有百分之三的含量，而且全都聚在了他的肉棒上！在这之后，精灵、半兽人、王宫贵族等一系列身份各异的美少女都来到了他的身边，渴求着被他的龙根征服...","name":"[木云汉化组]被召唤到异世界，然后成为半龙骑士长","latest_ep":"23","latest_ep_aid":"1022001","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"636173","author":"ERO404 五谷传教士 耀安","description":"","name":"人妻猎人 (官方正式版)","latest_ep":"68","latest_ep_aid":"1024376","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"467243","author":"あび ウメ种","description":"男性向“官能”小说大奖、“银奖”获奖作品！在远离村庄的某个洞穴里，诞生了不可能诞生的新“魔物”。在得到知性和欲望的时候，女冒险者会成为饵食——。","name":"隐秘洞窟的深处 \/ 淫靡洞窟的最深处 [あび、ウメ种] 淫靡な洞窟のその奥で (无圣光)","latest_ep":"30.2","latest_ep_aid":"1023919","image":"","category":{"id":"2","title":"单本"},"category_sub":{"id":null,"title":null}},{"id":"486760","author":"稻下竹刀 正玺","description":"故事讲述男主角阿久津东阳在搭乘公车时，遭遇死亡车祸，下个瞬间醒来时，不知为何身处小时候很热衷游玩的RPG游戏，然而身份却是魔王军四天王中的最弱角。为了打破原本在初期便会死亡的结局，男主角决定用BUG技能来支配女性角色们的身心，究竟男主角能否在危机四伏的命运中倖存下去…？","name":"转生为初期就死掉的中boss~将女主人公眷属化来活下来~－靠着将女主角眷属化而倖存 [稻下竹刀 正玺] 转生したら序盘で死ぬ中ボスだった－ヒロイン眷属化で生き残る－","latest_ep":"13.3","latest_ep_aid":"1024312","image":"","category":{"id":"2","title":"单本"},"category_sub":{"id":null,"title":null}},{"id":"543039","author":"Genzo","description":"主角秦萧风为保护马路上逗留的小女孩舍命相救，自己被车撞身亡，天使为奖励他将其穿越到生前喜欢看的国漫宇宙里 并得到一个逆天的催眠能力 但天使失手将能力发动位置由手部不小心传到了他的“老二”处 这以后会发生什么事情呢？","name":"国漫世界","latest_ep":"12","latest_ep_aid":"1023197","image":"","category":{"id":"4","title":"其他类"},"category_sub":{"id":null,"title":null}},{"id":"534227","author":"逢魔刻壹","description":"","name":"[しもやけ堂 (逢魔刻壹)] 妊活紫さん (东方Project) [白杨汉化组] [DL版]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"566986","author":"OB 加班慢郎中","description":"原本是系上边缘人的为廷，有一天偶然知道了系上正妹们的秘密…「你如果能替我保密…我愿意替你…」","name":"谁说理组没正妹?","latest_ep":"后记","latest_ep_aid":"645114","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"254931","author":"佐藤健悦 五里兰堂","description":"被传送到异世界的下之木健二和他的基友桐谷直人，在快要饿死的时候被一位好心的修女救了起来。在这个世界裡，每个人都有各自的天赋技能，基友凭藉其天赋技能“成长”快速升级，而直人却并未发现自己的天赋技能。为了守护天真的基友，直人外出获取情报，但却意外地被小混混袭击。就在这时，他的天赋技能显现了出来……","name":"异世界NTR～用最强技能让基友的女人恶堕 \/ 异世界Green hat man～用最强技能让基友的女人恶堕 \/ 【佐藤健悦 五里兰堂】异世界NTR~亲友のオンナを最强スキルで堕とす方法","latest_ep":"59","latest_ep_aid":"1024910","image":"","category":{"id":"2","title":"单本"},"category_sub":{"id":null,"title":null}},{"id":"466431","author":"猪肉 飞","description":"幽静的乡村，爷爷世代相传的天然温泉「万岁澡堂」。即将开业，独自负责澡堂运营的「镇浩」唯一的职员邻居姐姐「世静」和男儿将进行大扫除。整理仓库时偶然发现的可疑药草束和药材图鉴。用奇妙的香气浓郁的药材熬制的绿色草药汤让男女之间变得火热…！","name":"草药爱谈","latest_ep":"53","latest_ep_aid":"1025346","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"494719","author":"五色蜡笔 火红键盘","description":"成功到游乐园就职的宏建，梦想着可以成为掳获众人目光、带给大家欢乐的大哥哥，没想到再次遇上带给他悽惨童年的荞依。就在宏建得到一项神秘物品之后，一切都变了样…宏建慢慢受到女性员工们的瞩目，游乐园也渐渐变成「湿」乐园!","name":"命运湿乐园","latest_ep":"44","latest_ep_aid":"577926","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"322938","author":"1美金 卡玛地 烤海鲈鱼","description":"无意间穿越到异世界的西夫诺被赋预了绝对催眠以及射遍千万次也稳如泰山的超强精力!!西夫诺企图靠着催眠能力来打造属于自己的奴隶后宫!而他初次在异世界遇见的女人正是拥有曼妙身材的人妻?!","name":"异世界催眠王","latest_ep":"后记2","latest_ep_aid":"495443","image":"","category":{"id":"5","title":"韩漫"},"category_sub":{"id":null,"title":null}},{"id":"236959","author":"羽贺ソウケン 月夜泪","description":"回复术士只有治愈的才能。\r\n被认为一个人什么都做不到的存在。\r\n不依存别人就无法战斗，正因为是这样的存在所以被利用。\r\n一直被利用于是来到了这一步。\r\n在注意到过去的时候已经迟了，我的人生已经完了。\r\n所以重新来过。\r\n隐藏气息，不能让任何人知道我恢复了意识。装作十分愚钝，这也是为了最后最后的胜利。","name":"回复术士的重来人生\/回復术士的重启人生 [羽贺ソウケン,月夜泪] 回復术士のやり直し\/Kaifuku Jutsushi no Yarinaoshi","latest_ep":"65.1","latest_ep_aid":"636503","image":"","category":{"id":"2","title":"单本"},"category_sub":{"id":null,"title":null}},{"id":"422824","author":"しゅにち","description":"https:\/\/www.melonbooks.co.jp\/detail\/detail.php?product_id=1719255","name":"[黎欧出资汉化] [しゅにち关数 (しゅにち)] カルデア性活最高です -魔力供给まとめ本- (Fate\/Grand Order) [中国翻译] [DL版]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"351709","author":"あんこまん","description":"","name":"[黎欧x苍蓝星汉化组] [あんこまん] クリームヒルト、復讐の为に顽张る (Fate\/Grand Order) [中国翻译]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":null,"title":null},"category_sub":{"id":"1","title":"同人"}},{"id":"369670","author":"猫井ミィ","description":"","name":"[マンガスーパー (猫井ミィ)] マシュの花嫁修业 2 (Fate\/Grand Order) [中国翻译] [DL版]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}},{"id":"404144","author":"laliberte","description":"","name":"[超勇汉化组] [laliberte] FATE PART 1 color [中国翻译] [无修正]","latest_ep":null,"latest_ep_aid":null,"image":"","category":{"id":"1","title":"同人"},"category_sub":{"id":"1","title":"同人"}}],"folder_list":[],"total":"45","count":20}
1: invalid type: null, expected a string at line 1 column 9797
![2024-11-28_23-24](https://github.com/user-attachments/assets/ad0249cc-b503-4fb8-a5fe-e201f699f718)

**Comment by lanyeeee** [comment]
已在 [v0.11.0](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.11.0) 修复

**Comment by kingfirewxm** [comment]
> 已在 [v0.11.0](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.11.0) 修复

能成功获取收藏了，谢谢更新
