### ISSUE TITLE
[Bug] 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by doggybread** [lanyeeee/jmcomic-downloader#21]
### 问题描述

版本：jmcomic-downloader_0.3.0_x64-portable
问题：进入后搜索任何内容都显示错误提示框，搜索结果为空。

### 预期行为

显示搜索结果

### 实际行为

搜索结果为空

### 截图或录屏

![jm-err-01](https://github.com/user-attachments/assets/8f4076bc-aea4-4af9-a94b-569574bd5a9c)

### 工具版本号

0.3

### 其他

打开全局梯子也不行

**Comment by lanyeeee** [comment]
这是网络问题，多换几条魔法线路试试
