### ISSUE TITLE
[Bug] 预料之外的状态码(403 Forbidden): <title>Just a moment...</title>

### ISSUE THREAD

**Issue by liuhaoyu121** [lanyeeee/jmcomic-downloader#22]
### 问题描述

0: 收藏/取消收藏 失败，预料之外的状态码(403 Forbidden): <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-

### 预期行为

0: 收藏/取消收藏 失败，预料之外的状态码(403 Forbidden): <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-

### 实际行为

0: 收藏/取消收藏 失败，预料之外的状态码(403 Forbidden): <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-

### 工具版本号

0.3

**Comment by lanyeeee** [comment]
这是风控了，魔法换条线路试试，之后会优化一下错误提示

**Comment by lanyeeee** [comment]
我自己试了一下，所有接口都`预料之外的状态码(403 Forbidden): <title>Just a moment...</title> `了，明明今天中午还好好的。。。
又试了一些jm的第三方客户端，全都没法用了
**看起来是jm那边给APP的接口也加上5秒盾了**(~~也可能5秒盾本来就有，是我用的魔法的线路全都风控了~~)

有遇到相同问题的欢迎留言

**Comment by lanyeeee** [comment]
已在[v0.4](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.4)修复
