### ISSUE TITLE
[功能请求] 能不能添加一个填写代理的功能，全局代理，其他软件跑流量太凶

### ISSUE THREAD

**Issue by doggod9999** [lanyeeee/jmcomic-downloader#34]
### 原因

全局代理可以登录下载，其他软件跑流量太凶

### 功能简述

增加一个填写代理的功能

### 功能逻辑

可填写代理，端口，用户名及密码（非必须）

**Comment by lanyeeee** [comment]
规则模式无法登录么？

**Comment by doggod9999** [comment]
用的v2ray自己搭建的梯子，没有规则模式，只有清除代理、全局、不改变系统代理、pac四种，是用不改变系统代理么？我去试试看。

**Comment by doggod9999** [comment]
除了自动配重系统代理，其他模式都无法登录，无法搜索，无法下载。

**Comment by lanyeeee** [comment]
这是符合预期的，下载器会自动使用当前的系统代理
如果没有系统代理，就是直连

**Comment by doggod9999** [comment]
<img width="270" alt="QQ拼音截图20241015092940" src="https://github.com/user-attachments/assets/85690b2a-27c8-4ba3-b401-b2f03c64eb68">
只有第二项可以登录并下载。

**Comment by doggod9999** [comment]
> 这是符合预期的，下载器会自动使用当前的系统代理 如果没有系统代理，就是直连

是internet explorer的代理么？

**Comment by lanyeeee** [comment]
![image](https://github.com/user-attachments/assets/1b09cfe0-d72d-456f-b444-34d576269e83)

**Comment by lanyeeee** [comment]
这些一般都不需要用户手动改，代理软件会自动设置
你的截图里，第二项的意思就是由代理软件自动设置系统代理

**Comment by doggod9999** [comment]
可以了，改了一下internet选项，局域网设置里面的代理端口填上后，可以登录并下载了，其实最好还是有一个可以单独填的地方，没有就算了，多谢制作软件。
