### ISSUE TITLE
[Bug] 大量下载时，部分章节状态会一直卡在等待中

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/jmcomic-downloader#37]
### 问题描述

当并发下载大量章节时，部分章节状态会一直卡在"等待中"，无法继续下载。
必须重启下载器才能继续下载这些卡住的章节。
复现条件：全选《电锯人2》中的所有章节并点击下载，其他章节下载完成后，会剩一些章节的状态一直显示"等待中"。

### 预期行为

并发下载时，每个章节都应成功下载。
如果发生网络错误，应该给出错误提示，或者在代码内直接进行错误处理，如重试。

### 实际行为

并发下载时，部分章节状态会卡在"等待中"，没有错误提示，并且不会自动重试或继续下载，必须手动重启下载器才能继续下载这些章节。

### 工具版本号

v0.5

### 其他

怀疑是并发获取`ChapterRespData`或者`scramble_id`时出现了网络错误，代码中缺少相应的错误处理逻辑，导致出现错误了也没有提示。

**Comment by kingfirewxm** [comment]
这个问题也还会出现，需要重启软件重新选择章节下载。
环境：debian12，版本jmcomic-downloader_0.10.0_linux_amd64.deb
