### ISSUE TITLE
[Bug] 登陆无法跳过cloudflare

### ISSUE THREAD

**Issue by stepbystepcode** [lanyeeee/jmcomic-downloader#49]
### 问题描述

登录账户时候，会返回cloudflare的html，找一个不干净的ip节点会出现这个问题。

### 预期行为

正常登录成功

### 实际行为

报错，弹窗返回cloudflare的html

### 截图或录屏

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/407fd33d-546f-4b72-8f06-5be7f40e8ca0">

### 工具版本号

v0.6

### 其他

python中有一个cloudscraper包可以解决跳过cf的问题，但是rust我不太熟悉了。

**Comment by lanyeeee** [comment]
遇到这个问题就换线路

`cloudscraper`没用，该过不去还是过不去，你可以试试下面的代码
```python
import cloudscraper

scraper = cloudscraper.create_scraper()
print(scraper.get("https://whmcs.sharon.io/index.php?rp=/store/hk-lite").text)
```

**Comment by stepbystepcode** [comment]
你的用法有问题，你可以测试下面两个代码：
# 直接请求跳转cf
```python
import requests
from bs4 import BeautifulSoup

url = "https://18comic.vip/album_download/1013176#"
response = requests.get(url)
print(f"Status code: {response.status_code}")

```
# 使用cloudscraper跳过cf
```python
from bs4 import BeautifulSoup
import cloudscraper
scraper = cloudscraper.create_scraper(
    browser={
        "browser": "chrome",
        "platform": "windows",
    },
)
url = "https://18comic.vip/photo/553656"
response = scraper.get(url)
print(f"The status code is {response.status_code}")

```

**Comment by lanyeeee** [comment]
你别用jm的网址，你用我上面代码的网址

**Comment by stepbystepcode** [comment]
解决的就是jm的问题其他的网址不重要

**Comment by stepbystepcode** [comment]
我是有的节点，一个能过，一个不能过，你是干净节点肯定都能过

**Comment by lanyeeee** [comment]
下载器用的是app接口，而不是网页的接口，你代码用的是网页接口。

我猜你提到的`一个能过，一个不能过`是指下载器里的表现，我猜这两个节点在网页的表现都是能过。

首先，你应该找一个不能过`https://18comic.vip/photo/553656`的节点
怎么找，用任意API测试软件直接发get请求，返回403的就是不能过
找到不能过的节点以后，用`cloudscraper`尝试发请求，看看能不能过

我让你用`https://whmcs.sharon.io/index.php?rp=/store/hk-lite`就是为了省去**找不能过的节点**这一步
因为对于这个网址，无论你用什么节点，都不能过
下面这段代码表明，对于稳定不能过的情况，`cloudscraper`没用
```python
import cloudscraper

scraper = cloudscraper.create_scraper()
print(scraper.get("https://whmcs.sharon.io/index.php?rp=/store/hk-lite").text)
```

我相信我已经表达得很清楚了，问题主要还是出在IP上，而不是是否使用`cloudscraper`
