### ISSUE TITLE
[Bug] 生成的pdf图片顺序错误

### ISSUE THREAD

**Issue by stepbystepcode** [lanyeeee/jmcomic-downloader#57]
### 问题描述

生成的pdf图片顺序完全是乱的

### 预期行为

生成正确的pdf

### 实际行为

生成的pdf图片顺序错误

### 截图或录屏

<img width="192" alt="image" src="https://github.com/user-attachments/assets/918de1e7-642b-4a66-af54-cead93058b17">

### 工具版本号

v0.8

**Comment by lanyeeee** [comment]
看来是因为rust标准库的遍历目录方法在windows和unix上的行为不同导致的

**Comment by lanyeeee** [comment]
已在 [v0.9.0](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.9.0) 修复
