### ISSUE TITLE
[功能请求] 能否批量更新自己漫画收藏

### ISSUE THREAD

**Issue by kingfirewxm** [lanyeeee/jmcomic-downloader#67]
### 原因

很感谢作者的工作，这款软件是我目前找到的最易用的jm下载器。并且还支持linux。
我现在下载了十几个漫画，考虑到后面更新这些漫画的时候，我需要点开这十几个漫画，然后再点击下载。过程还是比较繁琐的。

### 功能简述

我的漫画都是下载在同一个文件夹下面的，我看到对于已经下载过的章节，软件可以做到自动识别。并且软件可以登录账号，获取漫画收藏列表。
我想，可不可以在漫画收藏中添加一个批量更新的功能，批量下载漫画收藏里没有下载的那几话

### 功能逻辑

通过漫画收藏，批量下载还没下载的漫画

**Comment by lanyeeee** [comment]
已在 [v0.12.0](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.12.0) 实现

**Comment by kingfirewxm** [comment]
非常感谢，试用了一下，很完美。
并且之前大量下载会卡住的问题也消失了。
再次感谢作者
