### ISSUE TITLE
[Bug]  生成pdf时，获取尺寸失败

### ISSUE THREAD

**Issue by doggod9999** [lanyeeee/jmcomic-downloader#72]
### 问题描述

部分章节可以下载，但是生成pdf失败，显示获取尺寸失败

### 预期行为

下载章节失败
0: 获取 "D:\\jmdownload\\漫画下载\\弱點 弱點\\.下载中-第33话 67\\001.webp" 的尺寸失败
1: Format error decoding WebP: Invalid Chunk header: [52, 49, 46, 46]
2: Invalid Chunk header: [52, 49, 46, 46]
弱點 弱點 - 第33话 67

### 实际行为

下载中文件夹内有文件，但是无法创建pdf文件。

### 截图或录屏

![123](https://github.com/user-attachments/assets/df1334be-b580-4b21-8a5c-ff913f5bdeb5)

### 工具版本号

V0.12

**Comment by lanyeeee** [comment]
已在 [v0.13.0](https://github.com/lanyeeee/jmcomic-downloader/releases/tag/v0.13.0) 修复
